Assignment-9(Relationship)/objects/College__c.object
<CustomObject>
    <fields>
        <fullName>College_Established_On__c</fullName>
        <label>College Established On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>TollFree_Number__c</fullName>
        <label>TollFree Number</label>
        <type>Phone</type>
    </fields>
    <label>College</label>
    <nameField>
        <label>College Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colleges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

9 assignment(Relationship)/objects/Teacher__c.object
<CustomObject>
    <fields>
        <fullName>College__c</fullName>
        <label>College</label>
        <referenceTo>College__c</referenceTo>
        <relationshipLabel>Teachers</relationshipLabel>
        <relationshipName>Teachers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Teacher_Phone_Number__c</fullName>
        <label>Teacher Phone Number</label>
        <type>Phone</type>
    </fields>
    <label>Teacher</label>
    <nameField>
        <label>Teacher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

9 assignment(Relationship)/classes/RelationShipRecord.cls
public class RelationShipRecord {
    public RelationShipRecord(){
        //Insert College Detail
        College__c c1=new College__c();
        c1.Name='Psit college of Engineering';
        c1.Email_Address__c='psitkanpur@gmail.com';
        c1.TollFree_Number__c='0512-888-999';
        c1.College_Established_On__c=date.parse('17/07/1881');
        //Insert TeacherData
        Teacher__c t1=new Teacher__c();
        t1.Name='Mohd Owais';
        t1.College__c='Psit college of Engineering';
        t1.Teacher_Phone_Number__c='7379215315';
        t1.Email_Address__c='owaispsit99@gmail.com';
        insert c1;
        insert t1;
        
    }

}