objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Father_s_Name__c</fullName>
        <label>Father&apos;s Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Father_s_phone_Number__c</fullName>
        <label>Father&apos;s phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>OverAll_Grade__c</fullName>
        <label>OverAll Grade</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Roll_Number__c</fullName>
        <label>Roll Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <label>Student Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_of_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Year of Class</label>
        <referenceTo>Year_of_Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

9 assignment(Relationship)/classes/StudentYearofclass.cls
public class StudentYearofclass {
    public StudentYearofclass(){
        //Insert Year of Student
        Year_of_Class__c y1=new Year_of_Class__c();
        y1.Name='First Year';
        insert y1;
        //Insert Student Details
          Student__c s1 = new Student__c();
        s1.Student_Name__c = 'Mohd Owais';
        s1.Roll_Number__c = 2345;
        s1.Father_s_Name__c='Jamshed';
        s1.Father_s_phone_Number__c='9838816799';
        s1.Email_Address__c='owaispsit99@gmail.com';
        s1.OverAll_Grade__c ='A';
        insert s1;
    }

}