9 assignment(Relationship)/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Mentor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mentor</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Employees (Mentor)</relationshipLabel>
        <relationshipName>Employees1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trainer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trainer</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>Employees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Father_s_Name__c</fullName>
        <label>Father&apos;s Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Father_s_phone_Number__c</fullName>
        <label>Father&apos;s phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>OverAll_Grade__c</fullName>
        <label>OverAll Grade</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Roll_Number__c</fullName>
        <label>Roll Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <label>Student Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

9 assignment(Relationship)/classes/JunctionRelation.cls
public class JunctionRelation {
    public JunctionRelation(){
        //Insert Subject Name
        Subject__c s1=new Subject__c();
        s1.Name='Maths';
        //Insert Student Detail
          Student__c std = new Student__c();
        std.Student_Name__c = 'Amit';
        std.Roll_Number__c = 2345;
        std.Father_s_Name__c='Bhadana';
        std.Father_s_phone_Number__c='8009210100';
        std.Email_Address__c='amitbhadana99@gmail.com';
        std.OverAll_Grade__c ='b';
        insert s1;
        insert std;
        //Insert Employee Record
        Employee__c e1=new Employee__c();
        e1.Name='Arpit';
        e1.Mentor__c='Seemu Sir';
        e1.Trainer__c='Rajiv Sir';
    }

}